sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: azRdUznDg9HdJtRzbvoQlTvKsj782daU+2/9s5VnNIouuKK18dfgaUXX3NIEUx6+wBQ/8Ax5PeanVJszYcP6jvaab8KFePC9Xao8EesT1H6/YDUdlDAMseG78FMNBMSBKiGQNtiUDpfJoFq9B2Fv4GutxMlfBLaTWEwYDNzYewnlOBEjJNFfO+vHOJGE9DALEiyLfuXg48A6bSMu0HXCbV/Qg0KlXj0UB3X2VHN+y5Zge8eYf0XCv8SWlDV8NdQKdx2W+Yyp/IamMOt/KQlC94E30UEEQi4lOyrClOhImNe7pea+MxPtploYL/cZvmDFoj1Z/vcCeGMfw89sjPUZ49nJdCdXgWG013DYaHr3MSBKss5EVX/g5mF6+YfV8MiMEZ+mgjFrHjO7RaItNrELnLxWy26Yq+A6DQdK5T/c8XPEK6THLfanPCxjxBKvA9JOMYdNclyvDgmOstdSq/0HL5yEKNO1V0wcmPnxyjTjcKQBomxtvK1h9WvDL9P/nf+gxxJnI/5J/xX/M9L3laG163KxzqqWG5QUrc30V2WpV9QCx0llmq2f66cbgQI5fjtXGFCYiYbSz8lk/YUO6+zxkNhA+vUJG6SMCjGUIzUvXiTwWVxc7iRT4JdReVSqgaW+nEvOkVGtnPwxpDFJlVGPzFcWI9/Dpu65Lc8DwvrO35Q=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Valiant-Runaways_3706
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy